In [15]:
#import modules

import numpy as np
import os
import matplotlib.pyplot as plt
import pickle

from keras import layers
from keras import models
from keras import optimizers
from keras.preprocessing import image_dataset_from_directory
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.regularizers import l2
from keras.utils import to_categorical
from keras.utils import multi_gpu_model
from keras.utils import Sequence
from keras.models import load_model
from tensorflow.distribute import MirroredStrategy

#initialise random generator
rng = np.random.default_rng()

In [16]:
#Define FelixDataflow classes and functions.

class FelixSequence(Sequence):
    def __init__(self, x_set, y_set, batch_size, file_type):
        """Here self.x is a list of paths to file_type files. self.y is a
        corresponding list of labels."""
        self.x, self.y = x_set, y_set
        self.batch_size = batch_size
        self.file_type = file_type

    def __len__(self):
        return int(np.ceil(len(self.x) / float(self.batch_size)))

    def __getitem__(self, idx):
        batch_x = self.x[idx * self.batch_size:(idx + 1) * self.batch_size]
        batch_y = self.y[idx * self.batch_size:(idx + 1) * self.batch_size]
        return arrs_from_paths(batch_x, self.file_type), to_categorical(np.array(batch_y),10)

def gen_paths_labels(base_path):
    """A generator to yield (data-paths, corresponding labels) tuples for each
    segment of data (typically training, validation, and testing)."""
    for segment in sorted(os.listdir(base_path)):
        segment_path = os.path.join(base_path, segment)
        segment_paths = []
        segment_labels = []
        for label in os.listdir(segment_path):
            label_path = os.path.join(segment_path, label)
            for crystal in os.listdir(label_path):
                segment_paths.append(os.path.join(label_path, crystal))
                segment_labels.append(label)
        indexes = np.arange(len(segment_labels))
        rng.shuffle(indexes)
        yield [np.array(segment_paths)[indexes], np.array(list(map(int,segment_labels)))[indexes]]

def arrs_from_paths(paths, file_type):
    if file_type == "txt":
        return np.array([np.loadtxt(file_name) for file_name in paths])
    elif file_type == "npy":
        return np.array([np.load(file_name)[[0],:,:] for file_name in paths])

def felix_fit_new(model, batch_size, epochs, workers, AllPaths, file_type, patience):
    #AllPaths = [[TrainingPaths, TrainingThickness], [], []]
    """A fit function to allow validation and test data to be supplied via a
    generator."""
    
    best_val_acc = -np.inf
    
    best_model = None
    
    x = np.arange(0, epochs)
    
    train_seq = FelixSequence(AllPaths[0][0], AllPaths[0][1], batch_size, file_type)
    val_seq = FelixSequence(AllPaths[1][0], AllPaths[1][1], batch_size, file_type)
    test_seq = FelixSequence(AllPaths[2][0], AllPaths[2][1], batch_size, file_type)
    for epoch in range(epochs):
        print("-------------------------------------------------------------------------")
        print("Epoch", epoch+1, "/", epochs, ": ")
        print("Training: ")
        train_hist = model.fit(x = train_seq, epochs = epoch+1, workers = workers, initial_epoch = epoch, shuffle=True)

        print("Validation: ")
        val_hist = model.evaluate(x = val_seq, workers = workers)       
        epoch_acc = val_hist[1]
        if(epoch_acc > best_val_acc):
            best_model = model
            #model.save(NewPath+ModelName)
            print("The model improved from: ",best_val_acc, "to: ", epoch_acc)
            best_val_acc = epoch_acc
            patience_i = 0
        else:
            patience_i+=1
            print("The model did not improve, patience_i = ", patience_i)

        print("Epoch acc: ", epoch_acc)
        #val_hist[0][epoch] = avg_recon_loss
        if(patience_i > patience):
            print("Early Stopping, the model did not improve from: ", best_val_acc)
            break

    print("-------------------------------------------------------------------------")
    print("Testing: ")
    tst_hist = best_model.evaluate(test_seq, workers = workers)
    
    return tst_hist[1], best_model

    

In [17]:
def MakeThicknessList(ListPaths):
    Thickness = []
    for i in ListPaths:
        Thickness.append(int(i.split("/")[-1].split(".")[0]))
    Thickness = np.array(Thickness)
    return(Thickness)

def OpenTxt(Path):
    with open(Path) as textFile:
        lines = [line.split() for line in textFile]
    List = []
    for i in lines:
        List.append(i[0])
    return(List)


DataPath = "//home/ug-ml/felix-ML/classification/Classification000/DataPaths/"

TrainPathAll = OpenTxt(DataPath + "Train_0p1.txt")
ValPathAll = OpenTxt(DataPath + "Validation_0p1.txt")
TestPathAll = OpenTxt(DataPath + "Test_0p1.txt")

In [18]:
LimTrain = int(len(TrainPathAll) * 0.1)
LimVal = int(len(ValPathAll) * 0.1)
LimTest = int(len(TestPathAll) * 0.1)

TrainPath = TrainPathAll[0:LimTrain]
ValPath = ValPathAll[0:LimVal]
TestPath = TestPathAll[0:LimTest]

TrainThickness = MakeThicknessList(TrainPath)[0:LimTrain]
ValThickness = MakeThicknessList(ValPath)[0:LimVal]
TestThickness = MakeThicknessList(TestPath)[0:LimTest]




AllPaths = [[TrainPath,TrainThickness],[ValPath,ValThickness],[TestPath,TestThickness]]

In [19]:
#All paths

SaveDataPath = "/home/ug-ml/Documents/GitHub_BigFiles/SaveFolder" #Base directory of place you store information of models
SaveFolderName = "/Classifer_1" #Will create a folder and put in information about the outcome / inputs
ModelName = "/Model.hdf5"

NewPath = SaveDataPath + SaveFolderName
#Many variables

#Model Variables
input_shape = (1, 128, 128)

#Hyper parameters
learning_rate = 0.0005
l2_regularizer = 0.0001
loss = 'categorical_crossentropy'
optimizer = "RMSprop" #Not a variable ONLY used for a note
batch_size = 32
epochs = 50
ShuffleTrainData = True

#Call back variables
TrainingPatience = 8
CheckPointMonitor = 'val_acc'
EarlyStopMonitor = 'val_acc'

#CPU variables
CPUworkers = 16


#List the name of the variables you want to save in a file
VariableListName = ["input_shape", 
                   "learning_rate", "l2_regularizer", "loss", "optimizer", "batch_size", "epochs", "ShuffleTrainData",
                   "TrainingPatience", "CheckPointMonitor", "EarlyStopMonitor",
                   "CPUworkers"]

#List the variables in the same order as VariableListName
VariableListValues = [input_shape, 
                   learning_rate, l2_regularizer, loss, optimizer, batch_size, epochs, ShuffleTrainData,
                   TrainingPatience, CheckPointMonitor, EarlyStopMonitor,
                   CPUworkers]

In [20]:
def build_model(learning_rate, l2_regularizer, dense_layer_size, kernal_size, kernal_num, opt, drop, loss_func):
    
    dense_layer_size = int(dense_layer_size)
    kernal_size = int(kernal_size)
    #strategy = MirroredStrategy() #Allows multiple GPUs
    
    if loss_func == 0:
        acvt = 'relu'
    elif loss_func == 1:
        acvt = 'sigmoid'
    elif loss_func == 2:
        acvt = 'tanh'
        
    #with strategy.scope():
    model = models.Sequential()
    model.add(layers.Conv2D(kernal_num, (kernal_size, kernal_size),
                                     activation=acvt,
                                     data_format='channels_first',
                                     input_shape= input_shape))
    model.add(layers.MaxPooling2D((2, 2), data_format='channels_first'))
    model.add(layers.Conv2D(kernal_num, (kernal_size, kernal_size),
                                     data_format='channels_first',
                                     activation=acvt))
    model.add(layers.MaxPooling2D((2, 2), data_format='channels_first'))
    model.add(layers.Conv2D(kernal_num, (kernal_size, kernal_size),
                                     data_format='channels_first',
                                     activation=acvt))
    model.add(layers.MaxPooling2D((2, 2), data_format='channels_first'))
    model.add(layers.Flatten())
    model.add(layers.Dropout(drop))
    model.add(layers.Dense(dense_layer_size, activation=acvt,
                           kernel_regularizer = l2(l2_regularizer)))

    model.add(layers.Dense(10, activation='softmax',
                           kernel_regularizer = l2(l2_regularizer)))
    if opt == 0:
        model.compile(loss = loss,
                      optimizer = optimizers.RMSprop(learning_rate = learning_rate),
                      metrics=['acc'])
    elif opt == 1:
        model.compile(loss = loss,
                      optimizer = optimizers.SGD(learning_rate = learning_rate),
                      metrics=['acc'])
    return model

In [22]:
parameters = {"l2_regulariser": np.array([0.00005, 0.000075, 0.0001, 0.00025, 0.0005, 0.00075, 0.001, 0.0015, 0.002]),
             "batch_size": np.array([8, 12, 16, 24, 32, 48, 64, 86, 128]),
             "dense_layer_size":np.array([32, 48, 64, 86, 128, 186, 256, 336, 512]),
             "kernal_size": np.array([2, 3, 4, 5, 6, 7, 8, 9, 10]),
             "kernal_num": np.array([16, 25, 32, 48, 64, 86, 128, 186, 256]),
             "optimisers": np.array([0,1]),
             "dropout": np.array([0.1, 0.15, 0.2, 0.25, 0.275, 0.3, 0.35, 0.4, 0.45]),
             "loss_func": np.array([0,1,2])}
    
z = np.array([2,2,1,1,3,0,2,0])
prev_searched = np.array([[1,2,1,1,3,0,2,0]])

def neighbours(point, dircs):
    ns = dircs+point
    #print(dircs, point, prev_searched)
    return np.array([i for i in ns if (0<=i).all() and (i<9).all() and (0<=i[5]<2) and (0<=i[7]<3) and not (i == prev_searched).all(axis=1).any()]).astype(int)

def parameter_search(parameters, z, prev_searched, learning_rate):
    
    num_params = len(parameters)
    dircs = np.zeros(shape = (2*num_params, num_params))
    for i, dirc in enumerate(dircs):
        if i < num_params:
            dirc[i] = 1
        else:
            dirc[i-num_params] = -1
    
    best_params = {}
    for key in parameters:
        best_params[key] = np.nan

    best_metrics = {"test_loss": np.inf, "test_acc": -np.inf}

    best_hist = {"train_acc": np.zeros(shape = epochs),
                "train_loss": np.zeros(shape=epochs),
                "val_acc": np.zeros(shape = epochs),
                "val_loss": np.zeros(shape=epochs)}
    
    converged = False
        
    while not converged:
        print("ITERATING OVER:")
        neighs = neighbours(z, dircs)
        num_neighs = neighs.shape[0]
        print(neighs, num_neighs)

        if neighs.size == 0:
            print("No new neighbours available. Saving best model and parameter set so far.")
            #best_model.save(NewPath+ModelName)
            converged = True
            break

        step_params = np.array([parameters[key][neighs[:,j]] for j, key in enumerate(parameters)]).T
        #print(step_params)
                

        converged = True

        for i, param_set in enumerate(step_params):
            print("Parameter set ", i+1," of ", num_neighs,"+++++++++++++++++++++++++++++++++++++++++++++++++++.")

            model = build_model(learning_rate, param_set[0], param_set[2], param_set[3], param_set[4], param_set[5], param_set[6], param_set[7])

            test_acc, best_model = felix_fit_new(model, param_set[1].astype(int), epochs, CPUworkers, AllPaths, "npy", TrainingPatience)

            prev_searched = np.append(prev_searched, neighs[i].reshape(1,num_params), axis=0)

            if test_acc > best_metrics["test_acc"]:
                
                best_metrics["test_acc"] = test_acc
                
                for k, key in enumerate(best_params):
                    best_params[key] = param_set[k]

                z = neighs[i]
                
                #best_model.save(NewPath+ModelName)
                converged = False
        print("best params set:" )
        print(best_params)
        print("best metrics set:" )
        print(best_metrics)
                
parameter_search(parameters, z, prev_searched, learning_rate)

ITERATING OVER:
[[3 2 1 1 3 0 2 0]
 [2 3 1 1 3 0 2 0]
 [2 2 2 1 3 0 2 0]
 [2 2 1 2 3 0 2 0]
 [2 2 1 1 4 0 2 0]
 [2 2 1 1 3 1 2 0]
 [2 2 1 1 3 0 3 0]
 [2 2 1 1 3 0 2 1]
 [2 1 1 1 3 0 2 0]
 [2 2 0 1 3 0 2 0]
 [2 2 1 0 3 0 2 0]
 [2 2 1 1 2 0 2 0]
 [2 2 1 1 3 0 1 0]] 13
Parameter set  1  of  13 +++++++++++++++++++++++++++++++++++++++++++++++++++.
-------------------------------------------------------------------------
Epoch 1 / 50 : 
Training: 
354/354 [==============================] - 8s 23ms/step - loss: 1.7946 - acc: 0.3842
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 2.5190 - acc: 0.4211
The model improved from:  -inf to:  0.42105263471603394
Epoch acc:  0.42105263471603394
-------------------------------------------------------------------------
Epoch 2 / 50 : 
Training: 
Epoch 2/2
354/354 [==============================] - 8s 22ms/step - loss: 1.4391 - acc: 0.5470
Validation: 
42/42 [==============================] - 1s 22ms/step - loss: 1.9192 - acc: 

Epoch 43/43
354/354 [==============================] - 9s 25ms/step - loss: 0.1790 - acc: 0.9735
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 3.5731 - acc: 0.7248
The model did not improve, patience_i =  1
Epoch acc:  0.7248120307922363
-------------------------------------------------------------------------
Epoch 44 / 50 : 
Training: 
Epoch 44/44
354/354 [==============================] - 8s 24ms/step - loss: 0.1584 - acc: 0.9763
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 3.7122 - acc: 0.7188
The model did not improve, patience_i =  2
Epoch acc:  0.718796968460083
-------------------------------------------------------------------------
Epoch 45 / 50 : 
Training: 
Epoch 45/45
354/354 [==============================] - 9s 24ms/step - loss: 0.1484 - acc: 0.9783
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 3.3113 - acc: 0.7233
The model did not improve, patience_i =  3
Epoch acc:  0.7233082652091

Epoch 14/14
236/236 [==============================] - 8s 35ms/step - loss: 0.4683 - acc: 0.8515
Validation: 
28/28 [==============================] - 1s 22ms/step - loss: 2.3311 - acc: 0.6466
The model improved from:  0.6375939846038818 to:  0.646616518497467
Epoch acc:  0.646616518497467
-------------------------------------------------------------------------
Epoch 15 / 50 : 
Training: 
Epoch 15/15
236/236 [==============================] - 8s 35ms/step - loss: 0.4179 - acc: 0.8613
Validation: 
28/28 [==============================] - 1s 24ms/step - loss: 2.1814 - acc: 0.6436
The model did not improve, patience_i =  1
Epoch acc:  0.6436090469360352
-------------------------------------------------------------------------
Epoch 16 / 50 : 
Training: 
Epoch 16/16
236/236 [==============================] - 8s 34ms/step - loss: 0.3959 - acc: 0.8743
Validation: 
28/28 [==============================] - 1s 24ms/step - loss: 2.0265 - acc: 0.6797
The model improved from:  0.646616518497467 t

354/354 [==============================] - 8s 24ms/step - loss: 0.7789 - acc: 0.7503
Validation: 
42/42 [==============================] - 1s 17ms/step - loss: 1.7164 - acc: 0.6000
The model improved from:  0.5864661931991577 to:  0.6000000238418579
Epoch acc:  0.6000000238418579
-------------------------------------------------------------------------
Epoch 7 / 50 : 
Training: 
Epoch 7/7
354/354 [==============================] - 8s 24ms/step - loss: 0.6768 - acc: 0.7840: 0s - loss: 0.7
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 2.0568 - acc: 0.6211
The model improved from:  0.6000000238418579 to:  0.621052622795105
Epoch acc:  0.621052622795105
-------------------------------------------------------------------------
Epoch 8 / 50 : 
Training: 
Epoch 8/8
354/354 [==============================] - 8s 24ms/step - loss: 0.6015 - acc: 0.8035
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 2.3330 - acc: 0.6135
The model did not imp

Epoch 11/11
354/354 [==============================] - 8s 23ms/step - loss: 0.4139 - acc: 0.8678
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 2.3582 - acc: 0.6722
The model improved from:  0.6631578803062439 to:  0.6721804738044739
Epoch acc:  0.6721804738044739
-------------------------------------------------------------------------
Epoch 12 / 50 : 
Training: 
Epoch 12/12
354/354 [==============================] - 8s 23ms/step - loss: 0.3774 - acc: 0.8839
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 2.4540 - acc: 0.6887
The model improved from:  0.6721804738044739 to:  0.688721776008606
Epoch acc:  0.688721776008606
-------------------------------------------------------------------------
Epoch 13 / 50 : 
Training: 
Epoch 13/13
354/354 [==============================] - 8s 24ms/step - loss: 0.3354 - acc: 0.8971
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 2.5547 - acc: 0.6722
The model did not i

Epoch 33/33
354/354 [==============================] - 8s 23ms/step - loss: 0.1277 - acc: 0.9760
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 4.9095 - acc: 0.7218
The model did not improve, patience_i =  9
Epoch acc:  0.7218044996261597
Early Stopping, the model did not improve from:  0.7293233275413513
-------------------------------------------------------------------------
Testing: 
21/21 [==============================] - 0s 16ms/step - loss: 2.9539 - acc: 0.7207
Parameter set  5  of  13 +++++++++++++++++++++++++++++++++++++++++++++++++++.
-------------------------------------------------------------------------
Epoch 1 / 50 : 
Training: 
354/354 [==============================] - 8s 22ms/step - loss: 1.8436 - acc: 0.4042
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 2.0551 - acc: 0.4496
The model improved from:  -inf to:  0.44962406158447266
Epoch acc:  0.44962406158447266
--------------------------------------------------

42/42 [==============================] - 1s 22ms/step - loss: 2.0051 - acc: 0.5023
The model improved from:  0.482706755399704 to:  0.5022556185722351
Epoch acc:  0.5022556185722351
-------------------------------------------------------------------------
Epoch 4 / 50 : 
Training: 
Epoch 4/4
354/354 [==============================] - 9s 25ms/step - loss: 1.1469 - acc: 0.6426
Validation: 
42/42 [==============================] - 1s 18ms/step - loss: 1.6771 - acc: 0.5353
The model improved from:  0.5022556185722351 to:  0.5353383421897888
Epoch acc:  0.5353383421897888
-------------------------------------------------------------------------
Epoch 5 / 50 : 
Training: 
Epoch 5/5
354/354 [==============================] - 8s 24ms/step - loss: 0.9915 - acc: 0.6764
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 1.5890 - acc: 0.5624
The model improved from:  0.5353383421897888 to:  0.5624060034751892
Epoch acc:  0.5624060034751892
----------------------------------

Epoch 7/7
354/354 [==============================] - 8s 24ms/step - loss: 1.6316 - acc: 0.4666
Validation: 
42/42 [==============================] - 1s 19ms/step - loss: 1.7808 - acc: 0.4105
The model improved from:  0.39849624037742615 to:  0.410526305437088
Epoch acc:  0.410526305437088
-------------------------------------------------------------------------
Epoch 8 / 50 : 
Training: 
Epoch 8/8
354/354 [==============================] - 8s 23ms/step - loss: 1.5390 - acc: 0.5005: 2s - loss: 1.5330 -  - ETA: 1s - l
Validation: 
42/42 [==============================] - 1s 22ms/step - loss: 1.7684 - acc: 0.4135
The model improved from:  0.410526305437088 to:  0.4135338366031647
Epoch acc:  0.4135338366031647
-------------------------------------------------------------------------
Epoch 9 / 50 : 
Training: 
Epoch 9/9
354/354 [==============================] - 9s 24ms/step - loss: 1.4671 - acc: 0.5285: 3s - loss: 1.51
Validation: 
42/42 [==============================] - 1s 22ms/step - l

354/354 [==============================] - 8s 23ms/step - loss: 0.6469 - acc: 0.8332
Validation: 
42/42 [==============================] - 1s 22ms/step - loss: 1.4054 - acc: 0.5895
The model improved from:  0.5804511308670044 to:  0.5894736647605896
Epoch acc:  0.5894736647605896
-------------------------------------------------------------------------
Epoch 29 / 50 : 
Training: 
Epoch 29/29
354/354 [==============================] - 9s 25ms/step - loss: 0.6258 - acc: 0.8349
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 1.4402 - acc: 0.5805
The model did not improve, patience_i =  1
Epoch acc:  0.5804511308670044
-------------------------------------------------------------------------
Epoch 30 / 50 : 
Training: 
Epoch 30/30
354/354 [==============================] - 9s 24ms/step - loss: 0.5980 - acc: 0.8508
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 1.3952 - acc: 0.5820
The model did not improve, patience_i =  2
Epoch acc:  

Epoch 50/50
354/354 [==============================] - 8s 24ms/step - loss: 0.3533 - acc: 0.9358
Validation: 
42/42 [==============================] - 1s 17ms/step - loss: 1.4499 - acc: 0.6135
The model improved from:  0.6120300889015198 to:  0.6135338544845581
Epoch acc:  0.6135338544845581
-------------------------------------------------------------------------
Testing: 
21/21 [==============================] - 0s 16ms/step - loss: 1.4826 - acc: 0.6066
Parameter set  9  of  13 +++++++++++++++++++++++++++++++++++++++++++++++++++.
-------------------------------------------------------------------------
Epoch 1 / 50 : 
Training: 
472/472 [==============================] - 8s 18ms/step - loss: 1.8725 - acc: 0.3749
Validation: 
56/56 [==============================] - 1s 17ms/step - loss: 2.3464 - acc: 0.4436
The model improved from:  -inf to:  0.4436090290546417
Epoch acc:  0.4436090290546417
-------------------------------------------------------------------------
Epoch 2 / 50 : 
Trai

Epoch 21/21
472/472 [==============================] - 9s 19ms/step - loss: 0.2937 - acc: 0.9325
Validation: 
56/56 [==============================] - 1s 15ms/step - loss: 2.4968 - acc: 0.7053
The model improved from:  0.7007519006729126 to:  0.7052631378173828
Epoch acc:  0.7052631378173828
-------------------------------------------------------------------------
Epoch 22 / 50 : 
Training: 
Epoch 22/22
472/472 [==============================] - 8s 17ms/step - loss: 0.2469 - acc: 0.9348
Validation: 
56/56 [==============================] - 1s 18ms/step - loss: 2.8090 - acc: 0.6586
The model did not improve, patience_i =  1
Epoch acc:  0.6586466431617737
-------------------------------------------------------------------------
Epoch 23 / 50 : 
Training: 
Epoch 23/23
472/472 [==============================] - 9s 18ms/step - loss: 0.2545 - acc: 0.9367
Validation: 
56/56 [==============================] - 1s 17ms/step - loss: 2.8368 - acc: 0.7113
The model improved from:  0.705263137817382

Epoch 6/6
354/354 [==============================] - 8s 24ms/step - loss: 0.7603 - acc: 0.7554: 1s - loss: 0.7
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 1.9163 - acc: 0.5835
The model did not improve, patience_i =  1
Epoch acc:  0.583458662033081
-------------------------------------------------------------------------
Epoch 7 / 50 : 
Training: 
Epoch 7/7
354/354 [==============================] - 9s 24ms/step - loss: 0.6769 - acc: 0.7801: 2s - loss: 0.7044 - acc: 
Validation: 
42/42 [==============================] - 1s 22ms/step - loss: 1.6859 - acc: 0.6331
The model improved from:  0.5909774303436279 to:  0.6330826878547668
Epoch acc:  0.6330826878547668
-------------------------------------------------------------------------
Epoch 8 / 50 : 
Training: 
Epoch 8/8
354/354 [==============================] - 9s 24ms/step - loss: 0.6256 - acc: 0.7994: 1s - loss: 0.6287 - acc: 0.80 - ETA: 1s - loss: 0.6330 - acc: 0.7 - ETA: 1s - loss
Validation: 
42/42 [=

Epoch 27/27
354/354 [==============================] - 9s 24ms/step - loss: 0.1824 - acc: 0.9608: 1s - loss: 0
Validation: 
42/42 [==============================] - 1s 22ms/step - loss: 3.8913 - acc: 0.7083
The model improved from:  0.7067669034004211 to:  0.7082706689834595
Epoch acc:  0.7082706689834595
-------------------------------------------------------------------------
Epoch 28 / 50 : 
Training: 
Epoch 28/28
354/354 [==============================] - 9s 24ms/step - loss: 0.1718 - acc: 0.9647
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 3.9750 - acc: 0.7068
The model did not improve, patience_i =  1
Epoch acc:  0.7067669034004211
-------------------------------------------------------------------------
Epoch 29 / 50 : 
Training: 
Epoch 29/29
354/354 [==============================] - 8s 24ms/step - loss: 0.1630 - acc: 0.9624
Validation: 
42/42 [==============================] - 1s 18ms/step - loss: 5.0724 - acc: 0.7113
The model improved from:  0.7

Epoch 49/49
354/354 [==============================] - 8s 24ms/step - loss: 0.1623 - acc: 0.9781: 
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 4.7250 - acc: 0.7218
The model did not improve, patience_i =  2
Epoch acc:  0.7218044996261597
-------------------------------------------------------------------------
Epoch 50 / 50 : 
Training: 
Epoch 50/50
354/354 [==============================] - 8s 24ms/step - loss: 0.1101 - acc: 0.9832
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 5.0015 - acc: 0.7113
The model did not improve, patience_i =  3
Epoch acc:  0.7112782001495361
-------------------------------------------------------------------------
Testing: 
21/21 [==============================] - 0s 12ms/step - loss: 3.8890 - acc: 0.6997
Parameter set  11  of  13 +++++++++++++++++++++++++++++++++++++++++++++++++++.
-------------------------------------------------------------------------
Epoch 1 / 50 : 
Training: 
354/354 [======

Epoch 20/20
354/354 [==============================] - 9s 24ms/step - loss: 0.3483 - acc: 0.9014
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 2.6520 - acc: 0.6752
The model improved from:  0.6616541147232056 to:  0.6751879453659058
Epoch acc:  0.6751879453659058
-------------------------------------------------------------------------
Epoch 21 / 50 : 
Training: 
Epoch 21/21
354/354 [==============================] - 9s 24ms/step - loss: 0.3281 - acc: 0.9065
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 2.7181 - acc: 0.6857
The model improved from:  0.6751879453659058 to:  0.6857143044471741
Epoch acc:  0.6857143044471741
-------------------------------------------------------------------------
Epoch 22 / 50 : 
Training: 
Epoch 22/22
354/354 [==============================] - 9s 24ms/step - loss: 0.3036 - acc: 0.9157
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 3.1827 - acc: 0.6692
The model did not

354/354 [==============================] - 8s 24ms/step - loss: 0.5921 - acc: 0.8128
Validation: 
42/42 [==============================] - 1s 22ms/step - loss: 1.7558 - acc: 0.6331
The model improved from:  0.6045112609863281 to:  0.6330826878547668
Epoch acc:  0.6330826878547668
-------------------------------------------------------------------------
Epoch 13 / 50 : 
Training: 
Epoch 13/13
354/354 [==============================] - 9s 25ms/step - loss: 0.5525 - acc: 0.8259: 1s - loss: 0.56
Validation: 
42/42 [==============================] - 1s 19ms/step - loss: 1.7738 - acc: 0.6316
The model did not improve, patience_i =  1
Epoch acc:  0.6315789222717285
-------------------------------------------------------------------------
Epoch 14 / 50 : 
Training: 
Epoch 14/14
354/354 [==============================] - 8s 24ms/step - loss: 0.5227 - acc: 0.8386: 0s - loss: 0.5129 - a
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 2.6990 - acc: 0.5940
The model did n

Epoch 11/11
354/354 [==============================] - 9s 24ms/step - loss: 0.4439 - acc: 0.8667
Validation: 
42/42 [==============================] - 1s 19ms/step - loss: 1.9150 - acc: 0.6391
The model improved from:  0.6360902190208435 to:  0.6390977501869202
Epoch acc:  0.6390977501869202
-------------------------------------------------------------------------
Epoch 12 / 50 : 
Training: 
Epoch 12/12
354/354 [==============================] - 8s 23ms/step - loss: 0.3875 - acc: 0.8834
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 2.3087 - acc: 0.6707
The model improved from:  0.6390977501869202 to:  0.6706767082214355
Epoch acc:  0.6706767082214355
-------------------------------------------------------------------------
Epoch 13 / 50 : 
Training: 
Epoch 13/13
354/354 [==============================] - 9s 24ms/step - loss: 0.3873 - acc: 0.8929
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 2.2641 - acc: 0.6842
The model improve

42/42 [==============================] - 1s 19ms/step - loss: 1.7408 - acc: 0.6135: 0s - loss: 2.1205 - ac
The model improved from:  0.6120300889015198 to:  0.6135338544845581
Epoch acc:  0.6135338544845581
-------------------------------------------------------------------------
Epoch 8 / 50 : 
Training: 
Epoch 8/8
354/354 [==============================] - 8s 23ms/step - loss: 0.6193 - acc: 0.8116
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 1.8049 - acc: 0.6406
The model improved from:  0.6135338544845581 to:  0.6406015157699585
Epoch acc:  0.6406015157699585
-------------------------------------------------------------------------
Epoch 9 / 50 : 
Training: 
Epoch 9/9
354/354 [==============================] - 8s 23ms/step - loss: 0.5447 - acc: 0.8351
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 1.9299 - acc: 0.6526: 0s - loss: 1.6927 - acc: 0.71
The model improved from:  0.6406015157699585 to:  0.6526315808296204
Epoch acc

236/236 [==============================] - 8s 33ms/step - loss: 1.9170 - acc: 0.3448
Validation: 
28/28 [==============================] - 1s 23ms/step - loss: 3.2562 - acc: 0.3624
The model improved from:  -inf to:  0.36240601539611816
Epoch acc:  0.36240601539611816
-------------------------------------------------------------------------
Epoch 2 / 50 : 
Training: 
Epoch 2/2
236/236 [==============================] - 8s 34ms/step - loss: 1.4522 - acc: 0.5065: 0s - loss: 1.4772 - a
Validation: 
28/28 [==============================] - 1s 27ms/step - loss: 2.9091 - acc: 0.4075
The model improved from:  0.36240601539611816 to:  0.40751880407333374
Epoch acc:  0.40751880407333374
-------------------------------------------------------------------------
Epoch 3 / 50 : 
Training: 
Epoch 3/3
236/236 [==============================] - 8s 33ms/step - loss: 1.2647 - acc: 0.5900
Validation: 
28/28 [==============================] - 1s 26ms/step - loss: 1.9032 - acc: 0.4812
The model improved fr

Epoch 22/22
236/236 [==============================] - 8s 34ms/step - loss: 0.1815 - acc: 0.9509
Validation: 
28/28 [==============================] - 1s 27ms/step - loss: 3.2066 - acc: 0.7083
The model improved from:  0.7022556662559509 to:  0.7082706689834595
Epoch acc:  0.7082706689834595
-------------------------------------------------------------------------
Epoch 23 / 50 : 
Training: 
Epoch 23/23
236/236 [==============================] - 8s 34ms/step - loss: 0.1873 - acc: 0.9530
Validation: 
28/28 [==============================] - 1s 22ms/step - loss: 3.0459 - acc: 0.7128
The model improved from:  0.7082706689834595 to:  0.7127819657325745
Epoch acc:  0.7127819657325745
-------------------------------------------------------------------------
Epoch 24 / 50 : 
Training: 
Epoch 24/24
236/236 [==============================] - 8s 34ms/step - loss: 0.1665 - acc: 0.9604: 0s - loss: 0.1714 
Validation: 
28/28 [==============================] - 1s 25ms/step - loss: 3.2625 - acc: 0.70

14/14 [==============================] - 0s 12ms/step - loss: 3.7309 - acc: 0.6847
Parameter set  3  of  14 +++++++++++++++++++++++++++++++++++++++++++++++++++.
-------------------------------------------------------------------------
Epoch 1 / 50 : 
Training: 
354/354 [==============================] - 8s 24ms/step - loss: 1.9279 - acc: 0.3423
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 2.9753 - acc: 0.4105
The model improved from:  -inf to:  0.410526305437088
Epoch acc:  0.410526305437088
-------------------------------------------------------------------------
Epoch 2 / 50 : 
Training: 
Epoch 2/2
354/354 [==============================] - 8s 24ms/step - loss: 1.4693 - acc: 0.5203
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 2.3912 - acc: 0.4150
The model improved from:  0.410526305437088 to:  0.415037602186203
Epoch acc:  0.415037602186203
-------------------------------------------------------------------------
Epoch 3 / 

Epoch 22/22
354/354 [==============================] - 8s 24ms/step - loss: 0.2346 - acc: 0.9480: 0s - loss: 0.2373 - a
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 3.5239 - acc: 0.6962
The model did not improve, patience_i =  3
Epoch acc:  0.6962406039237976
-------------------------------------------------------------------------
Epoch 23 / 50 : 
Training: 
Epoch 23/23
354/354 [==============================] - 8s 22ms/step - loss: 0.2077 - acc: 0.9509
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 3.5081 - acc: 0.6932
The model did not improve, patience_i =  4
Epoch acc:  0.693233072757721
-------------------------------------------------------------------------
Epoch 24 / 50 : 
Training: 
Epoch 24/24
354/354 [==============================] - 8s 24ms/step - loss: 0.1822 - acc: 0.9530
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 3.7553 - acc: 0.7188
The model improved from:  0.7037593722343445 to

Epoch 10/10
354/354 [==============================] - 9s 24ms/step - loss: 0.4771 - acc: 0.8452
Validation: 
42/42 [==============================] - 1s 18ms/step - loss: 2.1330 - acc: 0.6466
The model improved from:  0.630075216293335 to:  0.646616518497467
Epoch acc:  0.646616518497467
-------------------------------------------------------------------------
Epoch 11 / 50 : 
Training: 
Epoch 11/11
354/354 [==============================] - 9s 24ms/step - loss: 0.4465 - acc: 0.8650: 0s - loss: 0.460
Validation: 
42/42 [==============================] - 1s 13ms/step - loss: 2.6260 - acc: 0.6602
The model improved from:  0.646616518497467 to:  0.6601503491401672
Epoch acc:  0.6601503491401672
-------------------------------------------------------------------------
Epoch 12 / 50 : 
Training: 
Epoch 12/12
354/354 [==============================] - 8s 22ms/step - loss: 0.3902 - acc: 0.8770
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 2.1890 - acc: 0.6617
The

354/354 [==============================] - 8s 24ms/step - loss: 0.1237 - acc: 0.9715
Validation: 
42/42 [==============================] - 1s 19ms/step - loss: 5.2502 - acc: 0.7263
The model improved from:  0.7248120307922363 to:  0.7263157963752747
Epoch acc:  0.7263157963752747
-------------------------------------------------------------------------
Epoch 32 / 50 : 
Training: 
Epoch 32/32
354/354 [==============================] - 9s 24ms/step - loss: 0.1325 - acc: 0.9714
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 5.4474 - acc: 0.7068
The model did not improve, patience_i =  1
Epoch acc:  0.7067669034004211
-------------------------------------------------------------------------
Epoch 33 / 50 : 
Training: 
Epoch 33/33
354/354 [==============================] - 8s 23ms/step - loss: 0.1453 - acc: 0.9745
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 4.9680 - acc: 0.7248
The model did not improve, patience_i =  2
Epoch acc:  

Epoch 12/12
354/354 [==============================] - 8s 23ms/step - loss: 0.3224 - acc: 0.9040
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 2.4984 - acc: 0.6872
The model improved from:  0.6691729426383972 to:  0.6872180700302124
Epoch acc:  0.6872180700302124
-------------------------------------------------------------------------
Epoch 13 / 50 : 
Training: 
Epoch 13/13
354/354 [==============================] - 8s 22ms/step - loss: 0.2868 - acc: 0.9157
Validation: 
42/42 [==============================] - 1s 19ms/step - loss: 2.8760 - acc: 0.6977
The model improved from:  0.6872180700302124 to:  0.6977443695068359
Epoch acc:  0.6977443695068359
-------------------------------------------------------------------------
Epoch 14 / 50 : 
Training: 
Epoch 14/14
354/354 [==============================] - 8s 23ms/step - loss: 0.2733 - acc: 0.9258
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 3.3460 - acc: 0.6977
The model did not

Epoch 34/34
354/354 [==============================] - 6s 16ms/step - loss: 0.1159 - acc: 0.9800
Validation: 
42/42 [==============================] - 1s 17ms/step - loss: 4.5314 - acc: 0.7308
The model did not improve, patience_i =  6
Epoch acc:  0.7308270931243896
-------------------------------------------------------------------------
Epoch 35 / 50 : 
Training: 
Epoch 35/35
354/354 [==============================] - 7s 19ms/step - loss: 0.1214 - acc: 0.9813
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 4.4910 - acc: 0.7278
The model did not improve, patience_i =  7
Epoch acc:  0.727819561958313
-------------------------------------------------------------------------
Epoch 36 / 50 : 
Training: 
Epoch 36/36
354/354 [==============================] - 6s 18ms/step - loss: 0.1036 - acc: 0.9825
Validation: 
42/42 [==============================] - 1s 17ms/step - loss: 4.9491 - acc: 0.7188
The model did not improve, patience_i =  8
Epoch acc:  0.7187969684600

Epoch 18/18
354/354 [==============================] - 8s 24ms/step - loss: 2.1702 - acc: 0.1797
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 2.2578 - acc: 0.2301
The model improved from:  0.21353383362293243 to:  0.2300751805305481
Epoch acc:  0.2300751805305481
-------------------------------------------------------------------------
Epoch 19 / 50 : 
Training: 
Epoch 19/19
354/354 [==============================] - 8s 24ms/step - loss: 2.1591 - acc: 0.1981: 0s - loss: 2.1594 - ac
Validation: 
42/42 [==============================] - 1s 22ms/step - loss: 2.2747 - acc: 0.2211
The model did not improve, patience_i =  1
Epoch acc:  0.2210526317358017
-------------------------------------------------------------------------
Epoch 20 / 50 : 
Training: 
Epoch 20/20
354/354 [==============================] - 9s 25ms/step - loss: 2.1475 - acc: 0.2011: 0s - loss: 2.1497 - acc: 0. - ETA: 0s - loss: 2.1488 - ac
Validation: 
42/42 [==============================] - 1

Epoch 39/39
354/354 [==============================] - 9s 25ms/step - loss: 1.7690 - acc: 0.4274
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 2.4434 - acc: 0.3549
The model did not improve, patience_i =  2
Epoch acc:  0.3548872172832489
-------------------------------------------------------------------------
Epoch 40 / 50 : 
Training: 
Epoch 40/40
354/354 [==============================] - 9s 24ms/step - loss: 1.6582 - acc: 0.4449: 3s - loss: 1. - E
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 2.0044 - acc: 0.3759
The model improved from:  0.3593984842300415 to:  0.37593984603881836
Epoch acc:  0.37593984603881836
-------------------------------------------------------------------------
Epoch 41 / 50 : 
Training: 
Epoch 41/41
354/354 [==============================] - 8s 23ms/step - loss: 1.7270 - acc: 0.4325
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 2.3633 - acc: 0.3805
The model improved fro

42/42 [==============================] - 1s 21ms/step - loss: 3.4282 - acc: 0.7038
The model did not improve, patience_i =  7
Epoch acc:  0.7037593722343445
-------------------------------------------------------------------------
Epoch 31 / 50 : 
Training: 
Epoch 31/31
354/354 [==============================] - 9s 24ms/step - loss: 0.1689 - acc: 0.9622
Validation: 
42/42 [==============================] - 1s 17ms/step - loss: 3.3798 - acc: 0.7248
The model improved from:  0.7218044996261597 to:  0.7248120307922363
Epoch acc:  0.7248120307922363
-------------------------------------------------------------------------
Epoch 32 / 50 : 
Training: 
Epoch 32/32
354/354 [==============================] - 8s 24ms/step - loss: 0.1573 - acc: 0.9654
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 3.2043 - acc: 0.7218
The model did not improve, patience_i =  1
Epoch acc:  0.7218044996261597
-------------------------------------------------------------------------
Epoch

Epoch 2/2
354/354 [==============================] - 8s 22ms/step - loss: 2.2016 - acc: 0.1119
Validation: 
42/42 [==============================] - 1s 17ms/step - loss: 2.2009 - acc: 0.1113
The model did not improve, patience_i =  1
Epoch acc:  0.11127819865942001
-------------------------------------------------------------------------
Epoch 3 / 50 : 
Training: 
Epoch 3/3
354/354 [==============================] - 8s 23ms/step - loss: 2.2007 - acc: 0.1140
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 2.2007 - acc: 0.1098
The model did not improve, patience_i =  2
Epoch acc:  0.10977443307638168
-------------------------------------------------------------------------
Epoch 4 / 50 : 
Training: 
Epoch 4/4
354/354 [==============================] - 8s 23ms/step - loss: 2.2005 - acc: 0.1103
Validation: 
42/42 [==============================] - 1s 18ms/step - loss: 2.1998 - acc: 0.1113
The model did not improve, patience_i =  3
Epoch acc:  0.11127819865942001


Epoch 13/13
354/354 [==============================] - 8s 23ms/step - loss: 0.3655 - acc: 0.8925- ETA: 0s - loss: 0.3619 - acc: 0.
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 2.1367 - acc: 0.6647
The model improved from:  0.6616541147232056 to:  0.6646616458892822
Epoch acc:  0.6646616458892822
-------------------------------------------------------------------------
Epoch 14 / 50 : 
Training: 
Epoch 14/14
354/354 [==============================] - 7s 21ms/step - loss: 0.3286 - acc: 0.8938
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 2.3985 - acc: 0.6767
The model improved from:  0.6646616458892822 to:  0.6766917109489441
Epoch acc:  0.6766917109489441
-------------------------------------------------------------------------
Epoch 15 / 50 : 
Training: 
Epoch 15/15
354/354 [==============================] - 8s 23ms/step - loss: 0.2954 - acc: 0.9074
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 2.50

56/56 [==============================] - 1s 17ms/step - loss: 1.8584 - acc: 0.5624
The model improved from:  0.5593984723091125 to:  0.5624060034751892
Epoch acc:  0.5624060034751892
-------------------------------------------------------------------------
Epoch 6 / 50 : 
Training: 
Epoch 6/6
472/472 [==============================] - 9s 18ms/step - loss: 0.7525 - acc: 0.7586
Validation: 
56/56 [==============================] - 1s 16ms/step - loss: 1.7723 - acc: 0.6030
The model improved from:  0.5624060034751892 to:  0.6030074954032898
Epoch acc:  0.6030074954032898
-------------------------------------------------------------------------
Epoch 7 / 50 : 
Training: 
Epoch 7/7
472/472 [==============================] - 8s 18ms/step - loss: 0.6636 - acc: 0.7849
Validation: 
56/56 [==============================] - 1s 17ms/step - loss: 1.7056 - acc: 0.6075
The model improved from:  0.6030074954032898 to:  0.6075187921524048
Epoch acc:  0.6075187921524048
---------------------------------

Epoch 27/27
472/472 [==============================] - 8s 16ms/step - loss: 0.2067 - acc: 0.9609
Validation: 
56/56 [==============================] - 1s 16ms/step - loss: 3.5596 - acc: 0.6902
The model did not improve, patience_i =  4
Epoch acc:  0.6902255415916443
-------------------------------------------------------------------------
Epoch 28 / 50 : 
Training: 
Epoch 28/28
472/472 [==============================] - 9s 18ms/step - loss: 0.1664 - acc: 0.9590
Validation: 
56/56 [==============================] - 1s 15ms/step - loss: 3.7174 - acc: 0.7218
The model improved from:  0.7157894968986511 to:  0.7218044996261597
Epoch acc:  0.7218044996261597
-------------------------------------------------------------------------
Epoch 29 / 50 : 
Training: 
Epoch 29/29
472/472 [==============================] - 8s 17ms/step - loss: 0.1669 - acc: 0.9615
Validation: 
56/56 [==============================] - 1s 17ms/step - loss: 3.9317 - acc: 0.7068
The model did not improve, patience_i =  1


Epoch 49/49
472/472 [==============================] - 9s 18ms/step - loss: 0.1119 - acc: 0.9795
Validation: 
56/56 [==============================] - 1s 17ms/step - loss: 4.5464 - acc: 0.7263
The model did not improve, patience_i =  1
Epoch acc:  0.7263157963752747
-------------------------------------------------------------------------
Epoch 50 / 50 : 
Training: 
Epoch 50/50
472/472 [==============================] - 7s 15ms/step - loss: 0.1421 - acc: 0.9788
Validation: 
56/56 [==============================] - 1s 17ms/step - loss: 4.0917 - acc: 0.7128
The model did not improve, patience_i =  2
Epoch acc:  0.7127819657325745
-------------------------------------------------------------------------
Testing: 
28/28 [==============================] - 0s 12ms/step - loss: 3.5760 - acc: 0.7177
Parameter set  11  of  14 +++++++++++++++++++++++++++++++++++++++++++++++++++.
-------------------------------------------------------------------------
Epoch 1 / 50 : 
Training: 
354/354 [========

Epoch 5/5
354/354 [==============================] - 8s 23ms/step - loss: 0.8769 - acc: 0.7186
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 2.1592 - acc: 0.5759
The model improved from:  0.5639097690582275 to:  0.5759398341178894
Epoch acc:  0.5759398341178894
-------------------------------------------------------------------------
Epoch 6 / 50 : 
Training: 
Epoch 6/6
354/354 [==============================] - 8s 24ms/step - loss: 0.7749 - acc: 0.7427
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 1.7202 - acc: 0.5880
The model improved from:  0.5759398341178894 to:  0.5879698991775513
Epoch acc:  0.5879698991775513
-------------------------------------------------------------------------
Epoch 7 / 50 : 
Training: 
Epoch 7/7
354/354 [==============================] - 8s 24ms/step - loss: 0.7036 - acc: 0.7743
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 2.2248 - acc: 0.6226
The model improved from: 

Epoch 48/48
354/354 [==============================] - 9s 24ms/step - loss: 0.1277 - acc: 0.9772
Validation: 
42/42 [==============================] - 1s 19ms/step - loss: 6.0136 - acc: 0.7113
The model did not improve, patience_i =  2
Epoch acc:  0.7112782001495361
-------------------------------------------------------------------------
Epoch 49 / 50 : 
Training: 
Epoch 49/49
354/354 [==============================] - 8s 24ms/step - loss: 0.1255 - acc: 0.9793
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 4.9775 - acc: 0.7338
The model did not improve, patience_i =  3
Epoch acc:  0.7338345646858215
-------------------------------------------------------------------------
Epoch 50 / 50 : 
Training: 
Epoch 50/50
354/354 [==============================] - 8s 22ms/step - loss: 0.1222 - acc: 0.9814
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 5.1878 - acc: 0.7323
The model did not improve, patience_i =  4
Epoch acc:  0.732330799102

Epoch 19/19
354/354 [==============================] - 8s 21ms/step - loss: 0.3059 - acc: 0.9122
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 2.7859 - acc: 0.6932
The model improved from:  0.6736842393875122 to:  0.693233072757721
Epoch acc:  0.693233072757721
-------------------------------------------------------------------------
Epoch 20 / 50 : 
Training: 
Epoch 20/20
354/354 [==============================] - 8s 24ms/step - loss: 0.2901 - acc: 0.9162
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 3.0272 - acc: 0.6962
The model improved from:  0.693233072757721 to:  0.6962406039237976
Epoch acc:  0.6962406039237976
-------------------------------------------------------------------------
Epoch 21 / 50 : 
Training: 
Epoch 21/21
354/354 [==============================] - 7s 21ms/step - loss: 0.2677 - acc: 0.9208
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 3.3019 - acc: 0.6947
The model did not im

Epoch 41/41
354/354 [==============================] - 8s 24ms/step - loss: 0.1480 - acc: 0.9770- ETA: 2s - loss: 0.1638 - acc:
Validation: 
42/42 [==============================] - 1s 22ms/step - loss: 4.8017 - acc: 0.7173
The model did not improve, patience_i =  1
Epoch acc:  0.7172932624816895
-------------------------------------------------------------------------
Epoch 42 / 50 : 
Training: 
Epoch 42/42
354/354 [==============================] - 9s 25ms/step - loss: 0.1359 - acc: 0.9737
Validation: 
42/42 [==============================] - 1s 20ms/step - loss: 4.7097 - acc: 0.7053
The model did not improve, patience_i =  2
Epoch acc:  0.7052631378173828
-------------------------------------------------------------------------
Epoch 43 / 50 : 
Training: 
Epoch 43/43
354/354 [==============================] - 8s 23ms/step - loss: 0.1309 - acc: 0.9754
Validation: 
42/42 [==============================] - 1s 22ms/step - loss: 5.0929 - acc: 0.7113
The model did not improve, patience_i 

Epoch 34/34
354/354 [==============================] - 8s 23ms/step - loss: 0.1347 - acc: 0.9754: 0s - loss: 0.1
Validation: 
42/42 [==============================] - 1s 17ms/step - loss: 4.2908 - acc: 0.7203
The model did not improve, patience_i =  4
Epoch acc:  0.7203007340431213
-------------------------------------------------------------------------
Epoch 35 / 50 : 
Training: 
Epoch 35/35
354/354 [==============================] - 8s 24ms/step - loss: 0.1239 - acc: 0.9779
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 4.6632 - acc: 0.7098
The model did not improve, patience_i =  5
Epoch acc:  0.7097744345664978
-------------------------------------------------------------------------
Epoch 36 / 50 : 
Training: 
Epoch 36/36
354/354 [==============================] - 8s 23ms/step - loss: 0.1201 - acc: 0.9770
Validation: 
42/42 [==============================] - 1s 21ms/step - loss: 4.7399 - acc: 0.7158
The model did not improve, patience_i =  6
Epoch acc:

In [ ]:
print()

In [110]:
prev_searched = np.array([[0,1,2]])

learning_rate = np.array([0.0005, 0.0001, 0.001, 0.002, 0.005])
l2_regularizer = np.array([0.00005, 0.0001, 0.0005, 0.001, 0.002])
batch_size = np.array([8, 16, 32, 64, 128])

def neighbours(point):
    dircs = np.array([[0,0,1],[0,1,0],[1,0,0],[0,0,-1],[0,-1,0],[-1,0,0]])
    ns = dircs+point
    return np.array([i for i in ns if (0<=i).all() and (i<5).all() and not (i == prev_searched).all(axis=1).any()])


z = np.array([0,1,2])
converged = False
best_test_loss = np.inf
best_lr = np.nan
best_l2_r = np.nan
best_bs = np.nan

while not converged:
    print("ITERATING OVER:")
    neighs = neighbours(z)
    print(neighs)
    #print(neighs)
    if neighs.size == 0:
        print("No new neighbours available. Saving best model and parameter set so far.")
        np.save(NewPath+"/parameter_search.npy", np.array(best_lr,best_l2_r,best_bs))
        best_model.save(NewPath+ModelName)
        converged = True
        break
        

    lr = learning_rate[neighs[:,0]]
    l2_r = l2_regularizer[neighs[:,1]]
    bs = batch_size[neighs[:,2]]

    step_params = np.array([lr, l2_r, bs]).T
    
    converged = True
    
    for i, param_set in enumerate(step_params):
        
        model = build_model(param_set[0], param_set[1])
        
        test_loss, best_model = felix_fit_new(model, param_set[2].astype(int), epochs, CPUworkers, AllPaths, "npy", TrainingPatience)
        
        prev_searched = np.append(prev_searched, neighs[i].reshape(1,3), axis=0)
        
        if test_loss < best_test_loss:
            best_test_loss = test_loss
            best_lr = param_set[0]
            best_l2_r = param_set[1]
            best_bs = param_set[2]
            
            z = neighs[i]
            
            np.save(NewPath+"/parameter_search.npy",param_set)
            best_model.save(NewPath+ModelName)
            converged = False
            
    

ITERATING OVER:
[[0 1 3]
 [0 2 2]
 [1 1 2]
 [0 1 1]
 [0 0 2]]
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
-------------------------------------------------------------------------
Epoch 1 / 1 : 
Training: 
89/89 [==============================] - 7s 83ms/step - loss: 2.0421 - acc: 0.2734
Validation: 
11/11 [==============================] - 0s 29ms/step - loss: 2.5310 - acc: 0.3549
The model improved from:  inf to:  2.5309948921203613
Epoch loss:  2.5309948921203613
-------------------------------------------------------------------------
Testing: 
6/6 [==============================] - 0s 20ms/step - loss: 1.9448 - acc: 0.3724
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
-------------------------------------------------------------------------
Epoch 1 / 1 : 
Training: 
177/177 [=

In [112]:
print(best_lr,best_l2_r,best_bs)
print(best_test_loss)

0.0005 0.0005 32.0
1.822420358657837


In [38]:
test_seq = FelixSequence(AllPaths[2][0], AllPaths[2][1], best_bs.astype(int), "npy")
tst_hist = best_model.evaluate(test_seq, workers = 16)

11/11 [==============================] - 0s 10ms/step - loss: 1.6834 - acc: 0.6216


In [ ]:
#Build model
strategy = MirroredStrategy() #Allows multiple GPUs

with strategy.scope():
    model = models.Sequential()
    model.add(layers.Conv2D(128, (4, 4),
                                     activation='relu',
                                     data_format='channels_first',
                                     input_shape= input_shape))
    model.add(layers.MaxPooling2D((2, 2), data_format='channels_first'))
    model.add(layers.Conv2D(128, (4, 4),
                                     data_format='channels_first',
                                     activation='relu'))
    model.add(layers.MaxPooling2D((2, 2), data_format='channels_first'))
    model.add(layers.Conv2D(128, (4, 4),
                                     data_format='channels_first',
                                     activation='relu'))
    model.add(layers.MaxPooling2D((2, 2), data_format='channels_first'))
    model.add(layers.Flatten())
    model.add(layers.Dropout(0.25))
    model.add(layers.Dense(128, activation='relu',
                           kernel_regularizer = l2(l2_regularizer)))
    
    model.add(layers.Dense(10, activation='softmax',
                           kernel_regularizer = l2(l2_regularizer)))

    model.compile(loss = loss,
                  optimizer = optimizers.RMSprop(learning_rate = learning_rate),
                  metrics=['acc'])
    
#Make folder to put model and history information
try:
    os.mkdir(NewPath)
except:
    print("Folder failed to be created, it may already exist")
    
File1  = open(NewPath +"/Parameters.txt", "w+")
if(len(VariableListName) == len(VariableListValues)):
    for i in range(0, len(VariableListName)):
        File1.write(VariableListName[i] + " " + str(VariableListValues[i]) + "\n")
    File1.close()
else:
    print("VariableListName and VariableListValues do not match up, so file can not be saved")

In [ ]:
training_history = np.zeros(shape=(2,epochs))
validation_history = np.zeros(shape=(2,epochs))
test_history = [0,0]
#print(model.metrics_names)
felix_fit_new(model, batch_size, epochs, CPUworkers, AllPaths, "npy",TrainingPatience)